version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      CONFIG_CLASS: ProductionConfig
      #postgresql+pg8000://postgres:password@localhost/postgres
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://postgres:password@pg:5432/postgres
      FLASK_APP: app.py
      FLASK_ENV: production
    ports:
      - "8080:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data: